##################################################
### Normalizing Flow experiment configurations ###
##################################################
experiment_name: "glow_L=3_K=2"
phase: "train"

resume:
  # If resume_exp_dir is provided, then the training will be continued from resume_epoch epoch.
  resume_exp_dir: null  # The directory of experiment to resume the training.
  # resume_exp_dir has the form of ${experiment_name}_${now:%Y-%m-%d_%H-%M-%S}.
  resume_epoch: 0  # How many epochs the model has been trained.

data:
  name: "CelebA"  # One of ['CelebA', 'CIFAR10'].
  root: "/Users/davit/Desktop/thesis/experiments/data"
  batch_size: 16
  num_workers: 0
#  transformations: ["transformation1", "transformation2"]

model:
  architecture:
    L: 1
    K: 1

  training:
    epochs: 10  # The number of epochs to train or continue training.
    print_freq: 100
    val_freq: 1
    save_checkpoint_freq: 1

  testing:
    num_imp_samples: 10

  optimizer:
    type: "adam"
    lr: 1e-3


############################
### Hydra configurations ###
############################
hydra:
  run:
     dir: outputs/nf_experiments/${experiment_name}_${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
