##################################################
###### Normalizing Flow with Extended Prior ######
##################################################
experiment_name: ""
phase: "train"

resume:
  # If resume_exp_dir is provided, then the training will be continued from resume_epoch epoch.
  resume_exp_dir: null  # The directory of experiment to resume the training.
  # resume_exp_dir has the form of ${experiment_name}_${now:%Y-%m-%d_%H-%M-%S}.
  resume_epoch: 0  # How many epochs the model has been trained.


data:


model:
  name: "nf_extd"



############################
### Hydra configurations ###
############################
hydra:
  run:
     dir: outputs/nf_experiments/${experiment_name}_${now:%Y-%m-%d_%H-%M-%S}

# @package _global_
defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
